### ISSUE TITLE
Code no longer works

### ISSUE THREAD

**Issue by maxcalavera81** [one-love-420/Irrigation#2]
Good evening, first of all I would like to thank you for the fantastic work you did.
But unfortunately my watering stopped working, I think after updating to the latest version of HA. Simply when I try to activate automatic irrigation always has the last date and does not leave. Just like when I try to water manually nothing happens. But plugging directly into the solenoid valve switches works. Could you please see what may be causing such a problem. I have my watering system stopped without being able to water :(. Thanks in advance for all the attention available and I await feedback from you.

**Comment by maxcalavera81** [comment]
Sorry to be upset again. But your code stopped working again. Could you take a look at this great masterpiece? Thank you very much for your attention

**Comment by madzur** [comment]
I have the same issue. The scheduling options don't work anymore and the manual cycle runs don't work either. I am using HASS version 0.106.5 and I suspect it has something to to with abandoning groups in the newer releases. Unfortunately, the code is a bit too complex for me to revise, so I would really appreciate if the author could revisit the project and revise the code to support latest version of HASS.
Thanks a lot. it is really an elegant piece of code, bringing home automation to the next level.

**Comment by jacopoventura01** [comment]
good morning, the scheduling options don't work anymore and the manual cycle runs don't work either. I am using HASS version 0.106.2. The code is too complex for me to revise, so i really hope that the author could revise it. it's a fantastic code.

**Comment by madzur** [comment]
After doing some digging around, it seems this not working code is a matter of error in the irrigate_a_zone script.

When I try to manually run a cycle, the HA Log throws the following error:

> Error executing script script.irrigate_a_zone. Unknown error for condition at pos 1:
10:01:27 AM – Script (ERROR)

with the following details:
`Log Details (ERROR)
Logger: homeassistant.components.script
Integration: Script (documentation, issues)
First occured: 10:01:27 AM (1 occurences)
Last logged: 10:01:27 AM`

`Error executing script script.irrigate_a_zone. Unknown error for condition at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 283, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 331, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 469, in _async_check_condition
    check = config(self.hass, variables)
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 389, in template_if
    return async_template(hass, value_template, variables)
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 369, in async_template
    value = value_template.async_render(variables)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 221, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: can only concatenate str (not "int") to str`

I am suspecting some python programming errors, however, I’m not sure where to look.

Any idea how to resolve this?
